FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -v -o api ./cmd/api

FROM gcr.io/distroless/base

WORKDIR /app

COPY --from=builder /app/api .

EXPOSE 8080

CMD ["./api"]
